TA-5940 Upgrade dependencies: scala -> 2.13.10
gawkermedia/safe-config pull request #15
Opened 2023-06-12 13:46 UTC by nikodemkler

Bump dependencies versions:
Scala: "2.12.7" -> "2.13.10"
sbt: "1.6.1" -> "1.9.0"

2023-06-12 14:13 UTC, balagez requested changes

2023-06-12 14:13 UTC, balagez commented on README.md
> +Create your first config object:§
?

2023-06-12 14:13 UTC, balagez commented on build.sbt
> +crossScalaVersions := Seq(scalaVersion.value, "2.13.7", "2.12.15", "2.11.12")
1. Newest versions is 2.13.11
2. We don't need to build with `2.13.7`

2023-06-12 15:12 UTC, nikodemkler commented on build.sbt
> +wartremoverErrors ++= Warts.allBut(Wart.Equals, Wart.Overloading, Wart.ListAppend, Wart.IterableOps)
This one `Wart.IterableOps` is a bit more complicated to fix, let's keep it ignored for now

2023-06-13 14:37 UTC, balagez approved these changes

2023-06-13 15:34 UTC, merged